#!/usr/bin/env bash  

## Shortcuts
alias cd..='cd ..'
alias df='df -h'                          # human-readable sizes 
alias du='du -hcs'
alias grep='grep --color=tty -d skip'
alias la='ls -lah --group-directories-first --color=auto -F'
alias ll='ls -lh --group-directories-first --color=auto -F'
alias ls='ls --group-directories-first --color=auto -F'
#alias refresh='xrandr --output eDP1 --mode 2560x1440 --auto'

## single character aliases 
alias a='nano "$HOME"/.bash.d/aliases && source "$HOME"/.bashrc && echo "BASH Reloaded"'
alias b='nano "$HOME"/.bashrc && source "$HOME"/.bashrc && echo "BASH Reloaded"'
alias r='xrandr --output eDP1 --mode 2048x1152 --auto'
alias h='nano /etc/hosts'
alias c='cat'
alias l='clear' 
alias x='exit'
alias n='cd /etc/nginx'
alias t='nginx -t; systemctl restart nginx.service'

## Debian/Ubuntu Package Manager
alias install='apt install --noansweredit --noanswerdiff'
alias update='apt update'
alias upgrade='apt full-upgrade -y'
alias clean='apt autoremove -y && apt autoclean -y'
alias remove='apt purge -y' 
alias search='apt search "$1"'

## Arch Package Manger
#alias pacman='pacman'
#alias install='yay -S --answerclean all --answerdiff none --answeredit none --noconfirm "$@"'
#alias update='yay -Syu'
#alias remove='yay -Rs'
#alias clean='pacman -Rns $(pacman -Qtdq)'
#alias listpkgs="LC_ALL=C pacman -Qi | awk '/^Name/{name=$3} /^Installed Size/{print $4$5, name}' | sort -h'"
#alias search='yay "$1"'

# nano
alias bb="cd $HOME/.bash.d"
alias nanorc='nano /etc/nanorc' 
alias mirrorlist='nano /etc/pacman.d/mirrorlist'
alias pacconfig='nano /etc/pacman.conf'
alias authkeys='nano ~/.ssh/authorized_keys'
alias knownhosts="nano $HOME/.ssh/known_hosts"  
alias xi3='nano "${HOME}"/.i3/config'
alias xb='source "$HOME"/.bashrc && echo "BASH Reloaded"'
alias bashrc='nano "$HOME"/.bashrc && source "$HOME"/.bashrc && echo "BASH Reloaded"'
#alias grubdefault='nano /etc/default/grub; grub-mkconfig -o /boot/grub/grub.cfg; echo "Grub defaults updated! :)"' 
alias sshdconfig='nano /etc/ssh/sshd_config; systemctl restart sshd.service; echo "SSH Reloaded! :)"'
#alias sourceslist='nano /etc/apt/sources.list'
#alias xi3='nano ~/.i3/config' 
alias netinterfaceconf='nano /etc/network/interfaces'
alias iptableconf='nano /etc/iptables.conf'
alias termiteconf='nano ~/.config/termite/config'
alias ntpconf='nano /etc/ntp.conf'

## commands
alias startx='ssh-agent startx'
alias snap='snap'
alias shutdown='shutdown now' 
alias qq='cmatrix -a -C yellow -b -s -u 7'
alias matrix='cmatrix -a -C yellow -b -s -u 7'
alias neo='cmatrix -a -C yellow -b -s -u 7'
alias sdl='bash "$HOME"/.scripts/sdl.sh'
alias wpscan='ruby ~/wpscan/wpscan.rb'
alias wget="wget --hsts-file ~/dotfiles/config/wget/wget-hsts"

## File Utils
alias mkdir="mkdir -p"
alias rm='rm -r'

## File Permissions
alias chmod='chmod -R'
alias mod='chmod -R +x'
alias chown="chown -R $USER:$USER"
alias own="chown -R $USER:$USER"

## Compression
 
## Networking
alias ipwan='dig +short myip.opendns.com @resolver1.opendns.com'

## Locations
alias log='cd /var/log'
alias nginxdir='cd /etc/nginx'
alias www='cd /var/www/'
alias dots='cd $HOME/.dotfiles'
alias pline='cd $HOME/.local/lib/python3.6/site-packages/powerline/config_files/'
